import fs from 'fs';

const jobData = [
    {
        id: 1,
        date: "20 May, 2023",
        company: "New Age StartUp",
        position: "Senior React Developer",
        tags: ["Part Time", "3+ Years", "Night Shift"],
        location: "Minneapolis, Minnesota",
        salary: "$5000 - $6000/mth",
        color: "bg-red-200",
        isApplied: true,
    },
    {
        id: 2,
        date: "15 June, 2023",
        company: "Tech Innovators",
        position: "Backend Developer",
        tags: ["Full Time", "5+ Years", "Day Shift"],
        location: "San Francisco, California",
        salary: "$7000 - $8000/mth",
        color: "bg-blue-200",
        isApplied: false,
    },
    {
        id: 3,
        date: "10 July, 2023",
        company: "AI Pioneers",
        position: "Machine Learning Engineer",
        tags: ["Remote", "2+ Years", "Flexible"],
        location: "Remote",
        salary: "$9000/mth - $11000/mth",
        color: "bg-green-200",
        isApplied: true,
    },
    {
        id: 4,
        date: "1 August, 2023",
        company: "Data Analytics Corp",
        position: "Data Scientist",
        tags: ["Full Time", "5+ Years", "Flexible"],
        location: "Boston, Massachusetts",
        salary: "$8500 - $9500/mth",
        color: "bg-yellow-200",
        isApplied: false,
    },
    {
        id: 5,
        date: "5 September, 2023",
        company: "Cloud Masters",
        position: "DevOps Engineer",
        tags: ["Full Time", "4+ Years", "Day Shift"],
        location: "Seattle, Washington",
        salary: "$7500 - $8500/mth",
        color: "bg-purple-200",
        isApplied: true,
    },
    {
        id: 6,
        date: "10 October, 2023",
        company: "E-Commerce Hub",
        position: "Frontend Developer",
        tags: ["Remote", "3+ Years", "Flexible"],
        location: "Remote",
        salary: "$6500 - $7500/mth",
        color: "bg-pink-200",
        isApplied: false,
    },
    {
        id: 7,
        date: "20 November, 2023",
        company: "AI Solutions",
        position: "AI Researcher",
        tags: ["Part Time", "6+ Years", "Night Shift"],
        location: "Austin, Texas",
        salary: "$12000/mth - $13000/mth",
        color: "bg-teal-200",
        isApplied: true,
    },
    {
        id: 8,
        date: "5 December, 2023",
        company: "CyberShield",
        position: "Cybersecurity Analyst",
        tags: ["Full Time", "2+ Years", "Day Shift"],
        location: "New York, New York",
        salary: "$8000 - $9000/mth",
        color: "bg-gray-200",
        isApplied: false,
    },
    {
        id: 9,
        date: "10 January, 2024",
        company: "Blockchain Inc",
        position: "Blockchain Developer",
        tags: ["Remote", "5+ Years", "Flexible"],
        location: "Remote",
        salary: "$10000/mth - $11000/mth",
        color: "bg-indigo-200",
        isApplied: true,
    },
    {
        id: 10,
        date: "15 February, 2024",
        company: "Tech Savvy",
        position: "UI/UX Designer",
        tags: ["Full Time", "3+ Years", "Day Shift"],
        location: "Los Angeles, California",
        salary: "$7000 - $8000/mth",
        color: "bg-orange-200",
        isApplied: false,
    },
    {
        id: 11,
        date: "20 March, 2024",
        company: "HealthTech",
        position: "Full Stack Developer",
        tags: ["Full Time", "4+ Years", "Day Shift"],
        location: "Chicago, Illinois",
        salary: "$8500 - $9500/mth",
        color: "bg-cyan-200",
        isApplied: true,
    },
    {
        id: 12,
        date: "25 April, 2024",
        company: "GameWorks",
        position: "Game Developer",
        tags: ["Part Time", "2+ Years", "Night Shift"],
        location: "San Diego, California",
        salary: "$6000 - $7000/mth",
        color: "bg-lime-200",
        isApplied: false,
    },
    {
        id: 13,
        date: "30 May, 2024",
        company: "EduTech",
        position: "Education Technology Specialist",
        tags: ["Remote", "2+ Years", "Flexible"],
        location: "Remote",
        salary: "$7500/mth - $8500/mth",
        color: "bg-fuchsia-200",
        isApplied: true,
    },
    {
        id: 14,
        date: "5 June, 2024",
        company: "FinTech Pro",
        position: "Finance Engineer",
        tags: ["Full Time", "5+ Years", "Day Shift"],
        location: "Dallas, Texas",
        salary: "$9500 - $11000/mth",
        color: "bg-rose-200",
        isApplied: false,
    },
    {
        id: 15,
        date: "10 July, 2024",
        company: "StartUp Hub",
        position: "Marketing Analyst",
        tags: ["Part Time", "1+ Years", "Day Shift"],
        location: "San Jose, California",
        salary: "$4000 - $5000/mth",
        color: "bg-emerald-200",
        isApplied: true,
    },
    {
        id: 16,
        date: "15 August, 2024",
        company: "Retail Innovations",
        position: "Product Manager",
        tags: ["Full Time", "4+ Years", "Day Shift"],
        location: "Atlanta, Georgia",
        salary: "$10500 - $12000/mth",
        color: "bg-sky-200",
        isApplied: false,
    },
    {
        id: 17,
        date: "20 September, 2024",
        company: "Digital Cloud",
        position: "Cloud Architect",
        tags: ["Full Time", "6+ Years", "Day Shift"],
        location: "Phoenix, Arizona",
        salary: "$13000/mth - $15000/mth",
        color: "bg-violet-200",
        isApplied: true,
    },
    {
        id: 18,
        date: "25 October, 2024",
        company: "Social Impact Co.",
        position: "Community Manager",
        tags: ["Remote", "3+ Years", "Flexible"],
        location: "Remote",
        salary: "$5500 - $6500/mth",
        color: "bg-amber-200",
        isApplied: false,
    },
    {
        id: 19,
        date: "30 November, 2024",
        company: "EcoTech",
        position: "Environmental Engineer",
        tags: ["Full Time", "4+ Years", "Day Shift"],
        location: "Denver, Colorado",
        salary: "$9500 - $10500/mth",
        color: "bg-neutral-200",
        isApplied: true,
    },
    {
        id: 20,
        date: "5 December, 2024",
        company: "AI Next",
        position: "AI Operations Specialist",
        tags: ["Full Time", "5+ Years", "Night Shift"],
        location: "Remote",
        salary: "$11500/mth - $16500/mth",
        color: "bg-slate-200",
        isApplied: false,
    },
];

const salaryTypes = [
    { label: 'Per Month', value: 'Per Month' },
    { label: 'Per Year', value: 'Per Year' },
    { label: 'Per Hour', value: 'Per Hour' },
];

export const workLocations = [
    { label: 'Remote', value: 'Remote' },
    { label: 'Onsite', value: 'Onsite' },
    { label: 'Hybrid', value: 'Hybrid' },
];


const newData = jobData.map((job) => {
    const obj = {
        id: job.id,
        date: job.date,
        company: job.company,
        workExp: job.tags[1],
        schedule: job.tags[0],
        minSalary: parseInt(job.salary.replace('/mth', '').replace(/ /g, '').split('-')[0]?.slice(1)),
        maxSalary: parseInt(job.salary.replace('/mth', '').replace(/ /g, '').split('-')[1]?.slice(1)),
        color: job.color,
        position: job.position,
        isApplied: job.isApplied,
        shift: job.tags[2],
        salaryType: salaryTypes[Math.floor(Math.random() * salaryTypes.length)].label,
        tags: job.tags,
        location: job.location,
        salary: job.salary,
        locationType: workLocations[Math.floor(Math.random() * workLocations.length)].label
    }

    return obj
})

fs.writeFileSync('test2.js', JSON.stringify(newData))